import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import { join, basename } from "path";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Filenames are generated by snag/upload as `${Date.now()}-${rand6}.${ext}`.
// Accept only that shape so nothing else can be requested, and derive the
// content type from the validated extension instead of always claiming png.
const FILENAME_RE = /^[0-9]+-[a-z0-9]{6}\.(png|jpe?g|webp)$/;
const MIME: Record<string, string> = {
  png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp",
};

export async function GET(req: NextRequest) {
  const file = req.nextUrl.searchParams.get("file") ?? "";
  // basename strips any path component before the format check, defence in depth.
  if (file !== basename(file) || !FILENAME_RE.test(file)) {
    return NextResponse.json({ error: "invalid" }, { status: 400 });
  }
  const ext = file.split(".").pop()!;
  try {
    const buf = await readFile(join("/tmp/snags", file));
    return new NextResponse(buf, {
      headers: { "Content-Type": MIME[ext], "Cache-Control": "max-age=3600" },
    });
  } catch {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }
}
