"""Caterbook 'Arrivals and Departures' email PDF parser.

The email's PDF text comes out of pdfplumber as a flat string. Each PDF has
three sections (Arrivals / Stay throughs / Departures), each with one row
per (ref, room) combination. We parse to a list of observation dicts.

The status keyword ('To arrive', 'Checked in', 'Checked out') is the
reliable anchor: prefix has name+room+ref+room_type+rate+guests+contact,
suffix has balance + (departure date for stayovers).

Tested against 2025-11-19.pdf (the oldest email in the inbox).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime
from typing import Any


SECTION_HEADERS = {"Arrivals": "arrivals", "Stay throughs": "stayovers", "Departures": "departures"}

# Lines that are pure noise — skip.
NOISE_PATTERNS = [
    re.compile(r"^The Olde Malthouse Inn\s*$", re.I),
    re.compile(r"^Data as at:", re.I),
    re.compile(r"^Generated by Caterbook", re.I),
    re.compile(r"^Name Room Ref Room Type", re.I),
    re.compile(r"^Early\s*$", re.I),
    re.compile(r"^Late\s*$", re.I),
    re.compile(r"^check-in\s*$", re.I),
    re.compile(r"^check-out\s*$", re.I),
    re.compile(r"^\s*$"),
]

STATUS_TOKENS = ["To arrive", "Checked in", "Checked out", "Departed"]
BALANCE_RE = re.compile(r"£\s*([\d,]+\.\d{2})")
REF_RE = re.compile(r"\b(\d{3,6})\b")  # booking refs are 3-6 digits
DATE_RE = re.compile(r"\b(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b", re.I)
MONTH_ABBR = {m: i for i, m in enumerate(
    ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], start=1)}


@dataclass
class Observation:
    section: str
    guest_name: str
    room: str
    ref: str
    room_type: str | None
    rate_code: str | None
    guests_code: str | None
    contact: str | None
    status: str | None
    balance: float | None
    departure_date_seen: date | None
    raw_line: str


def _find_status(line: str) -> tuple[str, int, int] | None:
    """Return (status, start, end) for the first matching status keyword in line, else None."""
    for tok in STATUS_TOKENS:
        i = line.find(tok)
        if i >= 0:
            return tok, i, i + len(tok)
    return None


def _parse_date_token(s: str, snapshot_year: int) -> date | None:
    """'21 Nov' → date(<year>, 11, 21). Year picked so the departure is on/after snapshot_year (handles year-end roll)."""
    m = DATE_RE.search(s)
    if not m:
        return None
    day = int(m.group(1))
    month = MONTH_ABBR[m.group(2).title()]
    return date(snapshot_year, month, day)


def _parse_line(line: str, section: str, snapshot_year: int) -> Observation | None:
    """Parse a single data row. Return None if it doesn't look like one."""
    line = line.strip()
    if not line or any(p.match(line) for p in NOISE_PATTERNS):
        return None

    status_match = _find_status(line)
    if not status_match:
        return None  # not a data row
    status, st_start, st_end = status_match

    prefix = line[:st_start].rstrip()
    suffix = line[st_end:].lstrip()

    bal_m = BALANCE_RE.search(suffix)
    if not bal_m:
        return None
    try:
        balance = float(bal_m.group(1).replace(",", ""))
    except ValueError:
        balance = None

    # Departure date only for stayovers — appears AFTER the balance.
    departure_date_seen = None
    if section == "stayovers":
        tail = suffix[bal_m.end():]
        departure_date_seen = _parse_date_token(tail, snapshot_year)

    # Parse the prefix: name + room + ref + room_type + rate + guests + (contact?)
    # Strategy: find the LAST 3-6 digit number = ref. Everything before is
    # name+room. Everything after is room_type, rate, guests, contact.
    refs = list(REF_RE.finditer(prefix))
    if not refs:
        return None
    ref_match = refs[-1] if len(refs) == 1 else None
    # Pick the ref that, when split, leaves at least 2 tokens before and 3 after
    for m in refs:
        before = prefix[:m.start()].split()
        after  = prefix[m.end():].split()
        if len(before) >= 2 and len(after) >= 3:
            ref_match = m
            break
    if ref_match is None:
        ref_match = refs[-1]

    ref = ref_match.group(1)
    before_tokens = prefix[:ref_match.start()].split()
    after_tokens  = prefix[ref_match.end():].split()
    if len(before_tokens) < 2 or len(after_tokens) < 3:
        return None

    # before_tokens: [name parts..., room]  — room is the last token
    room = before_tokens[-1]
    guest_name = " ".join(before_tokens[:-1]).strip()

    # after_tokens: [room_type, rate, guests, contact_parts...]
    room_type   = after_tokens[0]
    rate_code   = after_tokens[1] if len(after_tokens) > 1 else None
    guests_code = after_tokens[2] if len(after_tokens) > 2 else None
    contact     = " ".join(after_tokens[3:]).strip() or None

    return Observation(
        section=section,
        guest_name=guest_name,
        room=room,
        ref=ref,
        room_type=room_type,
        rate_code=rate_code,
        guests_code=guests_code,
        contact=contact,
        status=status,
        balance=balance,
        departure_date_seen=departure_date_seen,
        raw_line=line,
    )


def _extract_report_date(text: str) -> date | None:
    """Pull 'Data as at: 19/11/2025 05:01' from the header."""
    m = re.search(r"Data as at:\s*(\d{1,2})/(\d{1,2})/(\d{4})", text)
    if not m:
        return None
    return date(int(m.group(3)), int(m.group(2)), int(m.group(1)))


def parse_pdf_text(text: str) -> dict[str, Any]:
    """Parse a full PDF text into report_date + list of observations.

    Returns {'report_date': date, 'observations': [Observation, ...]}.
    """
    report_date = _extract_report_date(text)
    snapshot_year = report_date.year if report_date else date.today().year

    observations: list[Observation] = []
    current_section: str | None = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        # Section header?
        if line in SECTION_HEADERS:
            current_section = SECTION_HEADERS[line]
            continue
        if current_section is None:
            continue
        obs = _parse_line(line, current_section, snapshot_year)
        if obs is not None:
            observations.append(obs)

    return {
        "report_date": report_date,
        "observations": observations,
    }
