-- V279: full pipeline_registry coverage (generated by gen-canonical-crontab.py)
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('supervisor','sweep','scripts/u241-supervisor.sh','*/10 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''supervisor'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('rejection_digest','sweep','scripts/u33-rejection-digest.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''rejection_digest'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('calendar_sync','sweep','scripts/u62-calendar-sync.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''calendar_sync'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('freshness_watcher_u165','sweep','scripts/u165-freshness-watcher.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''freshness_watcher_u165'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('touchoffice_realtime','sweep','scripts/u33-touchoffice-realtime.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''touchoffice_realtime'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('pipeline_watchdog_u54','sweep','scripts/u54-pipeline-watchdog.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''pipeline_watchdog_u54'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('paperless_sync','sweep','scripts/u62-paperless-sync.sh','*/15 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''paperless_sync'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('hermes_sentinel','sweep','scripts/hermes-sentinel.sh','*/30 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''hermes_sentinel'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('cron_health_check','sweep','scripts/cron-health-check.py','*/30 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''cron_health_check'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('touchoffice_epos_bridge','sweep','scripts/touchoffice-to-epos.py','*/30 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''touchoffice_epos_bridge'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('hermes_proposal_watch','sweep','scripts/hermes-proposal-watch.sh','*/5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''hermes_proposal_watch'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('event_close_sweep','sweep','scripts/u239-event-close-sweep.sh','*/5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''event_close_sweep'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('dashboard_watchdog','sweep','scripts/u272-dashboard-watchdog.sh','*/5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''dashboard_watchdog'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('data_lane_router','sweep','scripts/u33-data-lane-router.sh','*/5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''data_lane_router'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('doc_classify','sweep','scripts/u68-doc-classify.sh','*/5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''doc_classify'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('n8n_token_renew','sweep','scripts/renew-n8n-vault-token.sh','0 */12 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''n8n_token_renew'' AND status=''ok''',24,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('reviews_scrape','sweep','scripts/u163-reviews-simple.sh','0 */3 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''reviews_scrape'' AND status=''ok''',6,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('u29_heartbeat','sweep','scripts/u29-heartbeat.sh','0 */6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''u29_heartbeat'' AND status=''ok''',12,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('backup_nightly','sweep','scripts/backup-nightly.sh','0 3 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''backup_nightly'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('auto_classify','sweep','scripts/auto-classify.py','0 5 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''auto_classify'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('tides_scrape','sweep','scripts/u133-scrape-tides.py','0 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''tides_scrape'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('workforce_sync','sweep','scripts/u29-workforce-sync.sh','0 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''workforce_sync'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('britishgas_portal','sweep','scripts/u268-britishgas-portal.sh','0 7 3 * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''britishgas_portal'' AND status=''ok''',792,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('touchoffice_headoffice_backfill','sweep','scripts/u274-touchoffice-headoffice-backfill.sh','13 4 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''touchoffice_headoffice_backfill'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('counterparty_resolve_invoices','sweep','scripts/u271-resolve-invoices.sh','13,43 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''counterparty_resolve_invoices'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('dojo_inbox_sweep','sweep','scripts/u135-dojo-inbox-sweep.sh','15 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''dojo_inbox_sweep'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('marketing_sweep','sweep','scripts/u236-marketing-sweep.sh','17 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''marketing_sweep'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('hermes_memory_bridge','sweep','scripts/run-bridge.sh','17 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''hermes_memory_bridge'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_pdf_extract','sweep','scripts/u35-invoice-pdf-extract.sh','20 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_pdf_extract'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('tanda_timesheets','sweep','scripts/u47-tanda-timesheets-sync.sh','20 2 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''tanda_timesheets'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('feedback_apply','sweep','scripts/u50-apply-feedback.sh','23 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''feedback_apply'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('vision_ocr_drain','sweep','scripts/u281-vision-ocr-drain.py','23 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''vision_ocr_drain'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('alert_stale_ack','sweep','scripts/u50-stale-ack.sh','25 6,18 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''alert_stale_ack'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('touchoffice_daily','sweep','scripts/u27-touchoffice-daily.sh','30 3 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''touchoffice_daily'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('dext_sweep','sweep','scripts/u126-dext-export.sh','30 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''dext_sweep'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_forward_orphans','sweep','scripts/u128-forward-orphans.sh','30 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_forward_orphans'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('caterbook_daily','sweep','scripts/u28-caterbook-daily.sh','30 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''caterbook_daily'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('weather_sync','sweep','scripts/weather-sync.py','30 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''weather_sync'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('caterbook_guest_sync','sweep','scripts/u286-caterbook-guest-sync.sh','37 5 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''caterbook_guest_sync'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('proja_daily','sweep','scripts/projA-daily.sh','40 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''proja_daily'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('xero_export','sweep','scripts/u128-xero-export.sh','45 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''xero_export'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('claude_day','sweep','scripts/claude-day.sh','45 7 * * 1-5',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''claude_day'' AND status=''ok''',80,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_pdf_attach_fetch','sweep','scripts/u125-pdf-attachment-fetch.sh','5 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_pdf_attach_fetch'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('master_status_update','sweep','scripts/update-master-status.sh','50 23 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''master_status_update'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_harvester','sweep','scripts/u95-harvest-cron.sh','50 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_harvester'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('rota_alert','sweep','scripts/u280-rota-alert.sh','7 16 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''rota_alert'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('resume_watchdog','sweep','scripts/u250-resume-watchdog.sh','*/10 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''resume_watchdog'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_date_sweep','sweep','scripts/u-invoice-pdf-date-sweep.sh','10 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_date_sweep'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_line_sweep','sweep','scripts/u-invoice-line-sweep.sh','40 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_line_sweep'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('pipeline_freshness_watchdog','sweep','scripts/u-pipeline-freshness-watchdog.sh','5 */3 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''pipeline_freshness_watchdog'' AND status=''ok''',6,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('invoice_categorise','sweep','scripts/u-invoice-categorise-sweep.sh','30 6 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''invoice_categorise'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('natwest_inbox_sweep','sweep','scripts/u-natwest-inbox-sweep.sh','25 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''natwest_inbox_sweep'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('drinks_classify','sweep','scripts/u-drinks-classify-sweep.sh','50 7 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''drinks_classify'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('deadletter_hygiene','sweep','scripts/u-deadletter-hygiene.sh','25 * * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''deadletter_hygiene'' AND status=''ok''',2,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('revenue_recon','sweep','scripts/u-revenue-recon-check.sh','40 8 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''revenue_recon'' AND status=''ok''',26,
        'R0 heartbeat coverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('system_auditor','audit','scripts/u-system-auditor.py','30 5 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''system_auditor'' AND status=''ok''',26,
        'R0: nightly drift/integrity auditor') ON CONFLICT (name) DO NOTHING;
