-- V305 (2026-07-10) — bank rule pack round 3: multi-agent mining panel.
-- 50 candidates produced by 9 finder agents over the needs_review residue,
-- each adversarially verified against the full deduplicated ledger
-- (match counts, direction-vs-kind, counterparty homogeneity, bleed into
-- already-categorised rows). 43 rules after duplicate/overlap merges;
-- 28 clusters got principled abstentions (generic channel narratives,
-- family-name credits held for owner decision, heterogeneous merchants).
-- Full evidence: workflow wf_46241715-b83 journal.
INSERT INTO bank_transaction_rules
  (priority, name, description_re, type_in, amount_op, amount_value, entity_in, category, confidence, notes)
VALUES
  (150, 'Cornwall Council business rates (direct debit)', '^DIRECT DEBIT.*CORNWALL COUNCIL', NULL, '<', 0, ARRAY[1]::int[], 'tax_payment', 0.93, 'panel 2026-07-10, verified CONFIRMED; Recurring monthly direct debits to Cornwall Council on the main trading account (acct 15), two DD refs (802858250 fixed ~£101, 80285826X variable ~£505-£777) running 2021-2026 — classic business-rates instalment pattern for the pub premises. Existing rule 45 (''^CORNWALL COUNCIL'', tax_payment) already covers this exact category but is anchored to the start of t'),
  (151, 'Sian Libby Mills recurring personal payment', '^SIAN LIBBY MILLS , (FP [0-9]|CHILD MAINTENANCE , VIA ONLINE)', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.88, 'panel 2026-07-10, verified REFINED; 50 of 53 rows on Jo''s personal account (acct 6, entity 3) are an identical recurring monthly standing-order-style payment of exactly -£650.00 (2 more at the prior rate of -£540.28) running continuously 2021-12 through 2026-05, one row explicitly tagged ''CHILD MAINTENANCE''. This is a stable, single-purpose recurring personal outgoing on Jo''s own account — safe to'),
  (152, 'Dojo card-machine Direct Debit fee', '^Direct Debit DOJOUK PS32GC-GB', NULL, '<', 0, ARRAY[1]::int[], 'bank_fee', 0.90, 'panel 2026-07-10, verified CONFIRMED; All 25 needs_review rows matching ''DOJOUK PS32GC-GB'' are on account 15 (ATR Trading main), all Direct Debits, all negative, roughly monthly cadence 2024-01 to 2026-03, amounts £246-£1600. This is the merchant-service/card-terminal fee DD from Dojo (distinct from Dojo card-settlement credits, which are already covered by 3 existing rules requiring amount>0). Ze'),
  (153, 'Northcorn Linen supplier payment', 'NORTHCORN LINEN', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel 2026-07-10, verified CONFIRMED; Decisive sub-pattern inside the heterogeneous ''CONTRACT'' cluster: 5 needs_review rows all on account 15, all negative, all naming ''NORTHCORN LINEN'' as the payee inside the standard ''CONTRACT, VIA (ONLINE|MOBILE) - PYMT...MALTHOUSE MOBILE/ONLINE'' NatWest narrative. This is a linen-hire supplier for the pub (consistent with Malthouse trade-supplier conventions e'),
  (154, 'Jolyon Sandercock Cleeton rent transfer (ONLINE-PYMTB variant)', 'JOLYON SANDERCOCK CLEETON RENT', NULL, '<', 0, ARRAY[1]::int[], 'transfer_uncategorised', 0.92, 'panel 2026-07-10, verified CONFIRMED; Sub-pattern inside the ''JOLYON SANDERCOCK'' cluster. 6 byte-for-byte-equivalent sibling rows (same account 15, same -£1000.00, same ''JOLYON SANDERCOCK ... Cleeton rent'' text, monthly-ish cadence through 2024) already sit at transfer_uncategorised via the existing ''Internal Mobile Xfer'' rule (priority 40, matches literal ''VIA MOBILE''). These 3 needs_review rows '),
  (155, 'Pennon Water DD - ATR Trading (acct 15)', 'PENNON WATER SRVCS', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.92, 'panel 2026-07-10, verified CONFIRMED; 22 negative rows on acct 15 (ATR Trading main current), all ''Direct Debit PENNON WATER SRVCS 5006167601...'' -- a business water-rates DD, statement reference number confirmed constant across all rows. Entity 1 + negative sign cleanly isolates this account from the entity-1 Cap on Tap card rows (which are positive, handled separately below), so no overlap.'),
  (156, 'Pennon Water - Cap on Tap card (acct 16)', 'PENNON WATER.*Card Ending', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.90, 'panel 2026-07-10, verified CONFIRMED; Card-account sign trap: acct 16 (Cap on Tap business credit card) inverts sign vs bank accounts, so positive = spend. 2 rows ''PENNON WATER SERVICES - EXETER - Card Ending: ...'', consistent with the existing convention on this account (297 already-categorised supplier_payment rows are all positive, £3.44-£22,719.63 range, so these £2,561/£2,839 charges fit squa'),
  (157, 'Pennon Water DD - personal (acct 6)', 'PENNON WATER', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.85, 'panel 2026-07-10, verified CONFIRMED; 19 negative rows on acct 6 (Jo personal main current), mix of plain ''PENNON WATER SRVCS'' and card-coded forms (''9897 10SEP20 , PENNON WATER , SERVICES , EXETER GB'') -- all the same personal water-rates biller, recurring quarterly-ish cadence, amounts £282-£1,275. Matches the account''s dominant existing convention (1,050 rows already categorised direct_debit). '),
  (158, 'Watson Fuels - Cap on Tap card (acct 16)', 'WATSON FUELS', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.92, 'panel 2026-07-10, verified CONFIRMED; 26 rows, all on acct 16 (Cap on Tap), all positive (£5.59-£932.19) -- fuel supplier, card-sign trap (positive=spend). Same ''T''/''B'' branch-code and 0000000-account variants all resolve to the same supplier. Matches the account''s established supplier_payment convention.'),
  (159, 'Amazon.co.uk - Cap on Tap card (acct 16)', '^AMAZON\.CO\.UK -', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.88, 'panel 2026-07-10, verified CONFIRMED; 220 rows, all on acct 16, all positive (£3.49-£784.99) -- prefix-anchored to ''AMAZON.CO.UK - <acct number>'' which is a distinct, consistently-formatted narrative from other Amazon variants on this same card (AMAZON*, AMZNMktplace, AMZNBusiness -- those include the 6 negative/refund rows and were deliberately left out by the anchor). Card-sign trap: positive=sp'),
  (160, 'NEST pension DD - broadened comma format (acct 15)', 'NEST[, ]*IT000005336182', NULL, '<', 0, ARRAY[1]::int[], 'wages', 0.85, 'panel 2026-07-10, verified REFINED; Existing rule id=97 (priority 207) uses description_re=''NEST IT'' with amount<0/entity=1 and already covers most NEST pension DDs -- but it requires the literal substring ''NEST IT'' with no separator, while these 28 missed rows are formatted ''NEST , IT000005336182'' (comma-space between NEST and the account reference), so the existing regex never matches. All 28 ro'),
  (161, 'NEST pension refund credit (acct 15)', 'Automated Credit NEST PENSION PMT', NULL, '>', 0, ARRAY[1]::int[], 'refund', 0.70, 'panel 2026-07-10, verified CONFIRMED; 2 small positive credits (£14.42, £38.92) on acct 15 labelled ''Automated Credit NEST PENSION PMT P<ref>'' -- the pension provider crediting back an overpayment/correction. Clean, distinct format from the DD debits, low value, decisive pattern.'),
  (162, 'simmons_ca_recurring_credit_income_rent', 'SIMMONS C A', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.75, 'panel 2026-07-10, verified CONFIRMED; 25 rows, all account 6 (Jo personal, entity 3), all positive Faster Payments credits, £400/mo (one early £1600 catch-up) from 2023-07 to 2025-10 with reference ''BILL''. Matches the existing house convention seen in rule id=102 (priority 212): a list of named individuals paying recurring amounts into account 6 is already categorised income_rent (tenant/lodger bi'),
  (163, 'roxanne_gunner_salutations_rent', 'ROXANNE GUNNER', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.92, 'panel 2026-07-10, verified CONFIRMED; 8 rows, all account 6 (entity 3), all £1300 Faster Payment credits monthly Jul-2025 to Mar-2026, reference ''3 SALUTATIONS'' — Salutations is a known Jo-personal property per project_properties_mortgages. This is decisive rental income from a named tenant at a specific address, directly analogous to the existing named-tenant income_rent rules (id=102/103/106). N'),
  (164, 'amznmktplace_captontap_card16_supplier_payment', 'AMZNMKTPLACE.*CARD ENDING', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel 2026-07-10, verified CONFIRMED; This specific cluster head (''AMZNMKTPLACE - AMAZON.CO.UK - CARD ENDING:'') is exactly the account-16 Cap on Tap business-card narrative format (226 rows, all bank_account_id=16, entity_id=1). Account 16 already has 297 non-needs_review rows overwhelmingly categorised supplier_payment via near-identical vendor+''CARD ENDING'' rules (ids 82-85, 101) with amount_op '),
  (165, 'fdms_svcchg_paymentsense_bankfee', 'FDMS.*SVCCHG PAYMENTSENSE', NULL, '<', 0, ARRAY[1]::int[], 'bank_fee', 0.90, 'panel 2026-07-10, verified CONFIRMED; 16 rows, all account 15 (entity 1), all negative Direct Debits with the exact narrative ''DIRECT DEBIT FDMS , 510878762 SVCCHG PAYMENTSENSE LIMIT,'' spanning 2021-04 to 2023-06 — this is the card-machine service charge, distinct from card takings settlement. An existing rule (id=66, priority 117) already classifies ''PAYMENTSENSE'' matches as income_trading but ON'),
  (166, 'fdms_old_malthouse_card_settlement', 'ONLINE - PYMT MOBILE/ONLINE THE OLD MALTHOUSE , FDMS', NULL, '>', 0, ARRAY[1]::int[], 'card_settlement', 0.80, 'panel 2026-07-10, verified REFINED; 3 rows, all account 15 (entity 1), Aug 2020, positive amounts, exact phrase ''VIA/PYMT MOBILE/ONLINE THE OLD MALTHOUSE , FDMS'' — old-style (pre-Dojo-rebrand) card machine settlement narrative into the pub''s main account. Existing rule id=69 (card_settlement, ''FDEL FASTER PAYMEN|FDMS 510878762'', amount>0, entity 1) is the closest analog but misses these because th'),
  (167, 'BT GROUP direct debit (ARTL telecom)', 'BT GROUP', NULL, '<', 0, NULL, 'direct_debit', 0.90, 'panel 2026-07-10, verified REFINED; 58 rows, single account (15 = Atlantic Road Trading/pub), all debits, monthly recurring amounts £28-£603 over 2023-07 to 2026-03, narrative consistently ''Direct Debit BT GROUP PLC GP...'' with two separate DD reference series (...858920 and ...494218) — classic split phone/broadband billing. No existing rule covers BT GROUP; matches the established convention use'),
  (168, 'Arval UK Ltd vehicle lease DD (ARTL)', 'ARVAL UK LTD AT', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.85, 'panel 2026-07-10, verified CONFIRMED; 22 rows, single account (15 = ARTL/pub), all debits, one larger opening payment (-£2414.56, likely contract initiation + first instalment) followed by 21 near-identical monthly payments of -£268.28 (one month -£283.28) referencing the same contract ''AT9276'', from 2024-03 to 2025-12. Arval UK is a well-known commercial vehicle-leasing company — this is the pub'''),
  (169, 'DesignMyNight.com subscription DD (ARTL, debits only)', 'DESIGNMYNIGHT\.COM', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.85, 'panel 2026-07-10, verified CONFIRMED; 41 rows, single account (15 = ARTL/pub), all debits, monthly recurring £130-£581 from 2022-09 to 2026-05, narrative ''Direct Debit DESIGNMYNIGHT.COM 1101140'' (originally routed via Paymentsense/Dojo DD collection, later a plain DD). This is the pub''s booking-platform SaaS subscription fee, distinct from the existing rule 203 (card_settlement, ''ACCESS PAYSUITE..'),
  (170, 'Dojo/PaymentSense DD fee (DOJOUK PSXKKA)', 'DOJOUK PSXKKA', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.92, 'panel 2026-07-10, verified CONFIRMED; Distinct from the existing ''Dojo card settlement'' rules (id 4, priority 20; id 42, priority 45), which only match amount>0 (incoming settlement credits). These are outgoing Direct Debit collections by ''DOJOUK PSXKKA-GB<ref>'' on account 15 (Atlantic Road Trading) — Dojo/PaymentSense''s own recurring merchant-service/terminal fee collection, separate legal entity'),
  (171, 'GoCardless — Clearbrew DD (Direct Debit prefix variant)', 'CLEARBREW', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.95, 'panel 2026-07-10, verified CONFIRMED; Existing rule 37 (priority 45, ^GOCARDLESS) already classifies GoCardless-collected direct debits as direct_debit, and is proven correct for this exact vendor — 4 CLEARBREW rows already carry category=direct_debit where the description happens to start with the bare token ''GOCARDLESS , CLEARBREW-Z62AYBH5'' (2026 statement format). The needs_review rows are the '),
  (172, 'Novuna Personal Finance loan repayment (Hitachi Capital rebrand)', 'NOVUNA', NULL, '<', 0, ARRAY[3]::int[], 'loan_repayment', 0.95, 'panel 2026-07-10, verified CONFIRMED; Existing rule 27 (priority 45, ^HITACHI CAPITAL) already classifies this exact lender as loan_repayment — Novuna is Hitachi Capital Personal Finance''s 2021 rebrand, so the rule missed simply because the description text changed. All 12 rows are on account 6 (Jo personal, entity 3), fixed -453.08/month, exactly Mar 2022 to Feb 2023 (12 consecutive months, sum -'),
  (173, 'matthew_luxton_personal_standing_order', 'MATTHEW LUXTON', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.75, 'panel 2026-07-10, verified CONFIRMED; 21 rows, exact -£255.00 every month via Faster Payment standing order on Jo''s personal account (6), unbroken 2023-10-04 to 2025-06-04. No supplier/business narrative anywhere in the description (just name + FP timestamp), no counterparty registry match for Luxton. Same evidentiary shape as the existing precedent rule id 105 for MISS C A COLLINGS (regular fixed'),
  (174, 'eon_next_household_energy_dd', 'E\.ON NEXT', NULL, '<', 0, ARRAY[3,4]::int[], 'direct_debit', 0.85, 'panel 2026-07-10, verified CONFIRMED; Household energy supplier direct debits on Jo''s personal current account (6) and the Joint Account (10), 2025-04-28 to 2026-05-28, all debits, amounts step in plausible seasonal/tariff-review bands per account (£72-109 on acct 6, £222-343 on acct 10) consistent with two separate metered supplies billed monthly. No existing rule catches E.ON: rules 33/34 only a'),
  (175, 'gocardless_tamarkoffi_business_dd', 'TAMARKOFFI-BEMEM67', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.70, 'panel 2026-07-10, verified CONFIRMED; 26+ GoCardless-collected direct debits on the pub trading account (15), 2024-07-09 to 2025-12-19, all debits, variable amounts (£106-428) consistent with a usage-based service/subscription fee rather than a fixed rent-style payment. Existing rule id 37 (priority 45, ''^GOCARDLESS'') is anchored to the start of the description and misses these because the actual '),
  (176, 'Mobile — O2 (bare, no trailing token)', '^O2$', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.95, 'panel 2026-07-10, verified CONFIRMED; Existing rule 45 ''Mobile — O2'' requires ''^O2 '' (trailing space) and misses the bare 2-char description ''O2'' used in this feed''s format. 38 rows, all account 6 (Jo personal current), all negative, consistent -£17 to -£55 monthly mobile bill cadence 2019-2026.'),
  (177, 'Mobile — Vodafone Ltd DD', '^VODAFONE', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.95, 'panel 2026-07-10, verified CONFIRMED; No existing rule covers Vodafone. Account 6 only, monthly £24-£26.50 recurring mobile DD 2019-2020. One +£13.36 credit row exists (refund) and is deliberately excluded via amount<0.'),
  (178, 'Mobile — EE Ltd DD', '^EE LTD', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.95, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Account 6 only, consistent ~£38-41/mo mobile DD, 2025-2026.'),
  (179, 'Gym — GLL Better DD', '^GLL BETTER', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.93, 'panel 2026-07-10, verified CONFIRMED; No existing rule (Camelford Leisure rule 45 is a different named DD). Account 6 only, consistent £27.50-£30/mo gym membership DD 2021-2022, GLL/Better is a well-known UK leisure centre operator.'),
  (180, 'Fitness — Fitronics DD', '^FITRONICS', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.90, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Account 6 only, exact -£34.00 recurring monthly DD 2025-2026, fitness/gym membership software provider.'),
  (181, 'M&S Bank personal loan repayment DD', '^M&S LOANS', NULL, '<', 0, ARRAY[3]::int[], 'loan_repayment', 0.93, 'panel 2026-07-10, verified CONFIRMED; No existing rule; matches the style of existing NatWest/BBLS loan rules (lender+LOAN → loan_repayment). Account 6 only, consistent -£361/mo, 2025-2026.'),
  (182, 'ATM cash withdrawal (BMACH)', '^BMACH', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.88, 'panel 2026-07-10, verified CONFIRMED; No existing rule; 100% of BMACH rows are needs_review. Account 6 only, 4 cash-machine withdrawals 2019-2020, all negative round amounts (£40-£200) typical of personal ATM cash.'),
  (183, 'MyRewards cashback credit', '^MYREWARDS', NULL, '>', 0, ARRAY[3]::int[], 'income_other', 0.85, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Account 6 only, 20 rows all positive £5-£245, irregular cadence 2020-2025, consistent with a card/account cashback-rewards scheme paying into the current account.'),
  (184, 'Cornwall Council automated credit (rates refund/grant)', 'AUTOMATED CREDIT.*CORNWALL COUNCIL', NULL, '>', 0, ARRAY[1]::int[], 'income_other', 0.85, 'panel 2026-07-10, verified CONFIRMED; Same anchor mismatch as the DD variant but opposite direction. Account 15 only, 11 credits 2020-2025 ranging £132-£9000, consistent with business rates relief/grant refunds paid to the pub by the council (2020-21 rows align with COVID rates-relief grant period).'),
  (185, 'GoCardless aggregator DD (prefix variant)', 'DIRECT DEBIT.*GOCARDLESS', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.90, 'panel 2026-07-10, verified CONFIRMED; Existing rule 45 ''DD aggregator — GoCardless'' is anchored ^GOCARDLESS and misses rows prefixed ''Direct Debit '' / ''DIRECT DEBIT ,''. Account 15 only, 86 rows, all negative, various sub-merchants under the GoCardless rail (CLEARBREW, TAMARKOFFI, CELTICBOOKKE) — same generic direct_debit treatment as the existing rule applies to any GoCardless payee.'),
  (186, 'Caterbook Ltd DD (booking/EPOS subscription)', 'CATERBOOK LTD', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.90, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Account 15 only, 56 rows, consistent recurring negative £12-£319 direct debit to Caterbook Ltd, ref 3S2GGZY throughout — Caterbook is the pub''s known booking/EPOS platform (per memory).'),
  (187, 'BUPA Central A/C health insurance DD', 'BUPA CENTRAL', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.93, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Account 15 only, 37 rows, same A/C ref 0641664309 throughout, gradually rising premium £95.83→£126.08 across 2023-2026 — classic health-insurance DD escalation pattern.'),
  (188, 'Amazon marketplace — Cap On Tap card purchases', 'AMZNBusiness.*CARD ENDING', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.80, 'panel 2026-07-10, verified REFINED; Account 16 (Cap On Tap business card, entity 1) only. 590 rows, £34,734.53, all positive (=spend, inverted card sign). Precedent: 297 of the account''s already-classified rows are supplier_payment, matching the same ''named merchant + CARD ENDING'' pattern used by existing rule 211. Amazon wasn''t in rule 211''s explicit name list but the account is a dedicated busin'),
  (189, 'Named trade suppliers II — Cap On Tap card purchases (hardware/fuel/building)', '(THE HARDWARE SHOP|WATSON FUELS|TRAVIS PERKINS|TOOLSTATION|TOPPS TILES|WICKES).*CARD ENDING', NULL, '>', 0, ARRAY[1]::int[], 'supplier_payment', 0.90, 'panel 2026-07-10, verified CONFIRMED; Extends the existing rule-211 named-supplier list (same category, same account, same ''CARD ENDING'' anchor, same amount>0/entity 1 constraints) with six more clearly building/hardware/fuel trade suppliers seen repeatedly on the Cap On Tap card. 96 rows, £18,087.22. One negative Travis Perkins tool-hire refund row is deliberately excluded via amount>0.'),
  (190, 'ARE personal-property rent — named tenants (Lautier/Fenech, Hartley Home Care, G', '(LAUTIER|HARTLEY HOME CARE|GOODYER)', NULL, '>', 0, ARRAY[2]::int[], 'income_rent', 0.93, 'panel 2026-07-10, verified CONFIRMED; Matches the style of existing rule 212 (named-tenant surname → income_rent). Account 5 (ARE, entity 2) only, 49 rows total across three tenants: LAUTIER C A ref ''LAUTIER/FENECH'' (34 rows, consistent £550-£600/mo), HARTLEY HOME CARE explicitly tagged ''FLAT A LANGHOLME'' (11 rows, exact £750/mo — Langholme is a known ARE property per memory), and GOODYER M J expl'),
  (191, 'South West Water DD', '^SOUTH WEST WATER( |$)', NULL, '<', 0, NULL, 'direct_debit', 0.92, 'panel 2026-07-10, verified CONFIRMED; No existing rule. Household water DD across accounts 5, 6, and 10, all negative, 9 rows, £3801.90. Deliberately excludes the single outlier row ''SOUTH WEST WATER LTD EXETER'' (+£3766.08 on personal Mastercard acct 12 — different description format and a one-off card-style credit) via the anchored end-of-token match and separate amount>0 exclusion.'),
  (192, 'Reserve account interest credit (prefix/format variant)', 'INTEREST.*GRS 48885525', NULL, '>', 0, ARRAY[1]::int[], 'interest_credit', 0.95, 'panel 2026-07-10, verified CONFIRMED; Existing rule 10 is anchored to the exact format ''^[0-9]{1,2}[A-Z]{3} GRS [0-9]+$'' and misses rows where the feed adds ''TRANSACTION XFER INTEREST'', ''Interest'', or trailing ''£ £'' text around the same GRS reference. Account 20 only, 58 of the account''s 59 needs_review rows (the 59th is a one-off -£5000 director drawdown, deliberately excluded and left as needs_r')
ON CONFLICT DO NOTHING;
