-- V308 (2026-07-10) — bank rule pack round 4: mining panel round 2.
-- 37 candidates, 5 refuted by adversarial verifiers (incl. a Westcountry
-- rule that under-counted its blast radius 12->31 rows/£105k, and a
-- St Austell rule refuted on counterparty identity), 32 shipped.
-- Verifier-mandated priorities: the bare-FDMS catch-all at 220 (above the
-- pre-existing rule ceiling 213 — at the finder's 148 it would have
-- stolen an internal_transfer row); the personal card-format DEFAULT
-- (£241k of day-to-day spend) runs LAST at 235 so specific rules win.
-- Evidence: workflow wf_f15b2c36-85b journal.
INSERT INTO bank_transaction_rules
  (priority, name, description_re, type_in, amount_op, amount_value, entity_in, category, confidence, notes)
VALUES
  (220, 'fdms_bare_merchantno_faster_payment_settlement', '^AUTOMATED CREDIT 510878762 , FP', NULL, '>', 0, ARRAY[1]::int[], 'card_settlement', 0.90, 'panel r2 2026-07-10, REFINED; Owner-authoritative: faster-payment credits into trading accounts referencing acquirer merchant no. 510878762 are pay-by-bank card-terminal takings. These 15 rows carry the bare merchant number + ''FP <date> <time>'' structure without the literal word ''FDMS'', so they miss rule 120 (requires ''FDMS 510878762'' literal) and rule 117 (requires DOJO/PAYMENTSENSE text, which m'),
  (152, 'arval_uk_ltd_comma_variant', 'ARVAL UK LTD', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.95, 'panel r2 2026-07-10, CONFIRMED; Existing rule 168 requires literal ''ARVAL UK LTD AT'' (no comma) and correctly tags 22 rows direct_debit. These 2 needs_review rows use a comma-punctuated import variant ''ARVAL UK LTD , AT9276'' that breaks the anchor. Same vehicle-lease DD, same payee, just a punctuation drift between import batches - broadening to the payee name alone is safe since ARVAL UK LTD is a'),
  (153, 'nwb_business_loan_repayment', 'NWB BUSINESS LOAN', NULL, '<', 0, ARRAY[1]::int[], 'loan_repayment', 0.90, 'panel r2 2026-07-10, CONFIRMED; 3 rows, all identical -£831.86, same loan reference number 60000149473301, monthly cadence (Mar/Apr/May-Jun 2026) - a NatWest Business loan repayment, unambiguous and unmatched by any existing rule.'),
  (154, 'dojouk_ps32gc_comma_variant_fee', 'DOJOUK\s*,?\s*PS32GC-GB', NULL, '<', 0, ARRAY[1]::int[], 'bank_fee', 0.85, 'panel r2 2026-07-10, CONFIRMED; Existing rule 152 requires literal ''^Direct Debit DOJOUK PS32GC-GB'' and correctly tags 25 historical rows bank_fee (range -£246.70 to -£1600.90, avg -£863). These 2 needs_review rows drop the ''Direct Debit'' prefix and use a comma - a newer import format for the same Dojo card-machine account line; amounts (-£617.57, -£704.54) sit squarely inside the historical range'),
  (155, 'dojouk_psxkka_comma_variant_dd', 'DOJOUK\s*,?\s*PSXKKA-GB', NULL, '<', 0, ARRAY[1]::int[], 'direct_debit', 0.85, 'panel r2 2026-07-10, CONFIRMED; Existing rule 170 requires literal ''DOJOUK PSXKKA'' (space, no comma) and correctly tags 26 historical rows direct_debit (range -£50.95 to -£798.59, avg -£265). These 2 needs_review rows use a comma-punctuated variant; amounts (-£205.46, -£244.62) fit the historical range.'),
  (156, 'tintagel_brewery_faster_payment', 'TINTAGEL BREWERY', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.90, 'panel r2 2026-07-10, CONFIRMED; 5 debit rows on the trading account, same genuine FP-reference structure (''<ref>N TINTAGEL BREWERY , MALTHOUSE MOBILE/ONLINE'') as WESTCOUNTRY FRUIT above; entity_in [1] naturally excludes the unrelated personal-card (-£10.00) and Cap-on-Tap card (+£1839.24) rows on this same payee that live on other accounts/entities.'),
  (157, 'padstow_brewery_faster_payment', 'PADSTOW BREWERY', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel r2 2026-07-10, CONFIRMED; 3 debit rows, same genuine FP-reference structure as the other brewery/supplier rules; only 3 rows but the reference-number-anchored structure is decisive and consistent.'),
  (158, 'sj_fisheries_faster_payment', 'S&J FISHERIES', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel r2 2026-07-10, CONFIRMED; 4 debit rows, consistent genuine FP-reference structure (''<ref>N S&J FISHERIES , MALTHOUSE MOBILE/ONLINE''), fish supplier for the kitchen department, no contamination found.'),
  (159, 'wt_scaffold_faster_payment', 'WT SCAFFOLD', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel r2 2026-07-10, CONFIRMED; 4 debit rows, consistent genuine FP-reference structure, scaffolding/maintenance trade supplier, no contamination found.'),
  (160, 'cp_nitro_faster_payment_reference_anchored', '[0-9]{10,20}N\s+CP NITRO', NULL, '<', 0, ARRAY[1]::int[], 'supplier_payment', 0.85, 'panel r2 2026-07-10, CONFIRMED; IMPORTANT: a bare ''CP NITRO'' regex is UNSAFE - 42 of 49 needs_review ''CP NITRO'' rows are actually unrelated small card purchases (Amazon, Plymouth, Wadebridge, Bodmin, Camelford, Perranporth retail) with ''CP NITRO LTD , MALTHOUSE'' bled onto the end from the next statement line during PDF extraction (same contamination family as NATWEST TYL / XERO UK LTD / PARTNERSHI'),
  (161, 'standing_order_transf_bare_unlabeled', '^STANDING ORDER TRANSF', NULL, '<', 0, ARRAY[1]::int[], 'transfer_uncategorised', 0.70, 'panel r2 2026-07-10, CONFIRMED; 18 rows, every single one exactly -£900.00, a fixed recurring standing order (roughly monthly, 2021-2023) whose true destination is unrecoverable - the visible tails are all bleed-through from the next statement line (DOJO/PaymentSense references, Post Office, statement-footer boilerplate), not the standing order''s own payee. This mirrors the existing convention in '),
  (162, 'jolyon_sandercock_drawdown_repayment', '^TRANSACTION( VIA[A-Z -]*)? MOBILE/ONLINE JOLYON SANDERCOCK\s*,\s*(DRAWDOWN|REPAYMENT)', NULL, NULL, NULL, ARRAY[1]::int[], 'inter_entity_transfer', 0.80, 'panel r2 2026-07-10, REFINED; 3 rows on the trading account explicitly tagged ''JOLYON SANDERCOCK , DRAWDOWN'' or ''JOLYON SANDERCOCK , REPAYMENT'' - director''s loan/drawdown movement between Jo personally and ARTL, the same relationship existing rule 214 covers from the personal side (''Atlantic Road Trading...Drawdown/Director Loan'' -> inter_entity_transfer). Existing rule 40 (''SANDERCOCK J|MR J SAND'),
  (235, 'personal_card_format_default_spend', '^[0-9]{4} [0-9]{2}[A-Z]{3}[0-9]{2} ', NULL, '<', 0, ARRAY[3,4]::int[], 'personal_spend', 0.93, 'panel r2 2026-07-10, CONFIRMED; Standard UK card-transaction narrative (4-digit last-4 + DDMMMYY + CD/D token) on Jo''s personal/joint current accounts. VERIFIED this format also appears on the business trading account (15) with legitimate business subscriptions (Netflix, Google Workspace, Starlink, Indeed) - so entity_in is restricted to {3,4} (personal accounts 6,7,9 + joint 10 only), which never'),
  (228, 'personal_card_format_refund', '^[0-9]{4} [0-9]{2}[A-Z]{3}[0-9]{2}.*REFUND', NULL, '>', 0, ARRAY[3,4]::int[], 'refund', 0.92, 'panel r2 2026-07-10, CONFIRMED; Same card-narrative format as personal_card_format_default_spend but with explicit REFUND suffix and positive sign - a merchant refund of an earlier card purchase, not new spend.'),
  (163, 'atm_cash_multi_brand', '^(BARCLAYS BNK|LLOYDS BANK|HSBC|NATIONWIDE|NOTEMACHINE|GET CASH) [0-9]', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.95, 'panel r2 2026-07-10, CONFIRMED; ATM cash withdrawal narratives (bank/machine brand + DDMMM date, round-number amounts), the same pattern as the existing ^BMACH rule (id 141) but for other ATM operators/brands not previously captured. Confined entirely to account 6.'),
  (164, 'octopus_energy_dd', '^OCTOPUS ENERGY', NULL, '<', 0, ARRAY[3]::int[], 'direct_debit', 0.95, 'panel r2 2026-07-10, CONFIRMED; Recurring monthly household electricity DD, ~£150/mo. Distinct energy supplier from existing EDF/Opus Energy rules (id 33/34), which is why it was missed.'),
  (165, 'greenwich_leisure_gym', '^GREENWICH LEISURE', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.92, 'panel r2 2026-07-10, CONFIRMED; Recurring ~£38/month gym membership DD, consistent narrative and amount over 10 consecutive months in 2019-2020.'),
  (166, 'hac_yacht_club_dues', '^HAC YACHT', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.90, 'panel r2 2026-07-10, CONFIRMED; Annual £10 club subscription (Honourable Artillery Company yacht section), same FP narrative every 1 November for 7 consecutive years.'),
  (167, 'honourable_artillery_co_annual', '^HON(\.|OURABLE) ARTILLE', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.90, 'panel r2 2026-07-10, CONFIRMED; Annual membership subscription to the Honourable Artillery Company (companion payment to hac_yacht_club_dues, same organisation, gradually increasing fee), debited every 1 November for 7 consecutive years.'),
  (168, 'matt_luxton_recurring_payment', '^MATT LUXTON', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.88, 'panel r2 2026-07-10, CONFIRMED; Recurring £360 monthly standing order in 2023. An existing rule (id 132) already covers ''MATTHEW LUXTON'' -> personal_spend; this is the same recipient under a shorter narrative variant that the existing anchored regex misses.'),
  (169, 'exmay_grace_recurring_payment', '^EXMAY GRACE', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.82, 'panel r2 2026-07-10, CONFIRMED; Recurring £110/month personal payment to a named individual. Most rows with this payee already carry MOBILE XFER wording and are caught by the existing Internal Mobile Xfer rule (id 16, 25 rows); this covers the residual 6 rows using a plain FP narrative without that token.'),
  (170, 'dvla_vehicle_tax', 'DVLA', NULL, '<', 0, ARRAY[3]::int[], 'personal_spend', 0.90, 'panel r2 2026-07-10, REFINED; DVLA vehicle-tax payments referencing specific registration plates (WF60LFS, WL11HBA), unambiguous personal motoring cost.'),
  (171, 'postoffice_cash_deposit_bare', '^Post Office [0-9]{1,2}[A-Z]{3}$', NULL, '>', 0, ARRAY[3]::int[], 'cash_deposit', 0.90, 'panel r2 2026-07-10, CONFIRMED; Post Office counter cash deposits into account 6, same conceptual event as the existing rule (id 79) but a narrative variant that lacks the ''COUNTER'' token the existing regex anchors on. Verified exact strings have no trailing whitespace/garbage after the date token.'),
  (172, 'r_collins_salutations_rent', '^R COLLINS.*SALUTATIONS', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.92, 'panel r2 2026-07-10, CONFIRMED; Recurring monthly £1,100 rent credit explicitly referencing ''2 SALUTATIONS PL34'' (one of Jo''s personal rental units). Same family of rules as the existing personal-property-rent tenant list (id 102) which this named tenant was missing from.'),
  (173, 'harden_salutations_rent', '^HARDEN T&J/BLACK.*SALUTATIONS', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.90, 'panel r2 2026-07-10, CONFIRMED; Recurring £1,300 rent credit explicitly referencing ''3 SALUTATIONS'', a named tenant not in the existing rent-tenant rule set.'),
  (174, 'r_gunner_salutations_rent', '^R GUNNER.*SALUTATIONS', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.88, 'panel r2 2026-07-10, CONFIRMED; Rent credits explicitly referencing ''3 SALUTATIONS'' (same unit as HARDEN T&J/BLACK, apparent tenant succession). Distinct narrative from the existing ROXANNE GUNNER rule (id 122) which uses the full first name.'),
  (175, 'walker_castle_rd_rent', '^MISS K D WALKER.*CASTLE RD', NULL, '>', 0, ARRAY[3]::int[], 'income_rent', 0.90, 'panel r2 2026-07-10, CONFIRMED; Rent credits explicitly referencing ''FLAT, 1 CASTLE RD'', a personal rental property. Named tenant not in the existing tenant list (id 102).'),
  (176, 'atr_trading_salary_repayment_to_jo', '^ATLANTIC ROAD TRAD.*(SALARY|REPAYMENT)', NULL, '>', 0, ARRAY[3]::int[], 'inter_entity_transfer', 0.85, 'panel r2 2026-07-10, REFINED; Recurring £1,047.50 credits from the trading business to Jo''s personal account, labelled inconsistently as SALARY or REPAYMENT for the same recurring amount - a director drawing. Matches how 14 near-identical rows for the same payee are already independently categorised as inter_entity_transfer, confirming the bucket; these 4 rows use the same narrative and were simpl'),
  (177, 'tesco_bank_loan_drawdown', 'TESCO BANK LOAN', NULL, '>', 0, ARRAY[3]::int[], 'financing_advance', 0.70, 'panel r2 2026-07-10, CONFIRMED; Single £25,000 personal loan drawdown, unambiguous narrative (''MR JOLYON SANDERCO, TESCO BANK LOAN''). Only 1 row in the ledger today but the description is specific enough to be safe if it recurs.'),
  (178, 'postoffice_money_loan_drawdown', 'POSTOFFICE MONEY', NULL, '>', 0, ARRAY[3]::int[], 'financing_advance', 0.65, 'panel r2 2026-07-10, CONFIRMED; Single £24,100 credit from ''BANK OF IRELAND (U, POSTOFFICE MONEY'' - a personal loan drawdown under the Post Office Money brand. Only 1 row, positive-sign constraint keeps it disjoint from the existing debit-side Post Office Money DD rule (id 41, anchored ''^POSTOFFICE MONEY'').'),
  (179, 'duplicate_refund_marker', 'DUPLICATE REFUND', NULL, '>', 0, ARRAY[3]::int[], 'refund', 0.75, 'panel r2 2026-07-10, CONFIRMED; Single £5,520 credit explicitly labelled ''DUPLICATE REFUND'' - self-describing, low risk of false positives on any future row that reuses this exact wording.'),
  (180, 'capontap_nonCE_refund_adjustment', '(Rewards Redemption|Plan Refund|Adjustment -)', NULL, '<', 0, ARRAY[1]::int[], 'refund', 0.82, 'panel r2 2026-07-10, CONFIRMED; VERIFIED these three markers appear ONLY on account 16 (9 rows total system-wide). They are card-balance credits without the ''Card Ending:'' merchant format: rewards-points redemption, plan refunds, and dispute/goodwill adjustment reversals. All negative (balance-reducing, i.e. money back) under the confirmed inverted sign convention.')
ON CONFLICT DO NOTHING;
