-- pipeline_registry seed for canonical crontab entries
-- (generated by gen-canonical-crontab.py; idempotent; NOT a migration)
INSERT INTO ops.pipeline_registry(name,kind,script_path,schedule_cron,freshness_sql,freshness_sla_hours,notes)
VALUES ('system_auditor','audit','scripts/u-system-auditor.py','30 5 * * *',
        'SELECT max(finished_at) FROM ops.pipeline_runs WHERE name=''system_auditor'' AND status=''ok''',26,
        'R0: nightly drift/integrity auditor') ON CONFLICT (name) DO NOTHING;
