#!/bin/bash
# /home_ai/scripts/u169-gen-docs.sh
# Generate up-to-date docs from live state:
#   - docs/slug-catalog.md     — every active slug with display name + description + realm
#   - docs/sitemap.md          — every dashboard route grouped by section
#   - docs/cron-jobs.md        — every cron entry + grace window + last run
#   - docs/data-sources.md     — every ingest source + freshness + cadence
#
# Run autonomously; output is reproducible. Safe to re-run any time.

set -euo pipefail
mkdir -p /home_ai/docs
GEN_AT=$(date -u '+%Y-%m-%d %H:%MZ')

# ── 1. Slug catalog ──
docker exec homeai-postgres psql -U postgres -d homeai -tAc "
COPY (
  SELECT
    '## ' || slug || E'\n\n' ||
    '**Display:** ' || display_name || E'\n' ||
    '**Realm:** ' || realm || E'\n' ||
    CASE WHEN description IS NOT NULL AND description <> ''
      THEN '**Description:** ' || description || E'\n' ELSE '' END ||
    CASE WHEN param_schema::text <> '{}'
      THEN '**Params:** \`' || param_schema::text || E'\`\n' ELSE '' END ||
    E'\n'
  FROM query_whitelist
  WHERE active = true AND approved_at IS NOT NULL
  ORDER BY realm, slug
) TO STDOUT
" > /tmp/slug-bodies.md

cat > /home_ai/docs/slug-catalog.md <<EOF
# Slug catalog

_Auto-generated by u169-gen-docs.sh — do not hand-edit. Last run: $GEN_AT._

Every approved query_whitelist slug, callable via:

\`\`\`
GET /api/finance/slug/<slug>[?param=value]
\`\`\`

Realm header required (\`X-Realm: owner|work|personal\`).

Total active slugs: $(docker exec homeai-postgres psql -U postgres -d homeai -tAc "SELECT count(*) FROM query_whitelist WHERE active AND approved_at IS NOT NULL")

---

EOF
# COPY emits literal \n — unescape
sed 's|\\n|\n|g' /tmp/slug-bodies.md >> /home_ai/docs/slug-catalog.md
rm -f /tmp/slug-bodies.md

# ── 2. Cron jobs ──
cat > /home_ai/docs/cron-jobs.md <<EOF
# Cron jobs

_Auto-generated by u169-gen-docs.sh. Last run: $GEN_AT._

## Catalogued jobs (tracked by U168 wrapper)

| job_name | cron expr | grace_min | max_retries | command |
|---|---|---:|---:|---|
EOF
docker exec homeai-postgres psql -U postgres -d homeai -tAc "
COPY (
  SELECT '| ' || job_name || ' | \`' || cron_expr || '\` | ' || grace_minutes ||
         ' | ' || max_retries || ' | \`' || command || '\` |'
  FROM cron_job_catalog WHERE active ORDER BY job_name
) TO STDOUT
" >> /home_ai/docs/cron-jobs.md

cat >> /home_ai/docs/cron-jobs.md <<EOF

## Last 7 days outcomes

\`\`\`
EOF
docker exec homeai-postgres psql -U postgres -d homeai -c "
SELECT job_name, status, count(*) AS n
FROM cron_job_runs
WHERE expected_at > NOW() - INTERVAL '7 days'
GROUP BY 1,2 ORDER BY 1,2;" >> /home_ai/docs/cron-jobs.md
echo '```' >> /home_ai/docs/cron-jobs.md

cat >> /home_ai/docs/cron-jobs.md <<EOF

## Raw crontab (host user $(whoami))

\`\`\`
EOF
crontab -l 2>/dev/null | grep -vE "^#" | grep -v "^$" >> /home_ai/docs/cron-jobs.md
echo '```' >> /home_ai/docs/cron-jobs.md

# ── 3. Data sources ──
cat > /home_ai/docs/data-sources.md <<EOF
# Data sources

_Auto-generated by u169-gen-docs.sh. Last run: $GEN_AT._

Every upstream ingest source + freshness + expected cadence. Live snapshot:

| source | latest | expected_cadence_h | age_h | status |
|---|---|---:|---:|---|
EOF
docker exec homeai-postgres psql -U postgres -d homeai -tAc "
COPY (
  SELECT '| ' || source || ' | ' || COALESCE(latest::text, 'never') ||
         ' | ' || expected_h || ' | ' ||
         COALESCE(ROUND(EXTRACT(EPOCH FROM (NOW() - latest))/3600)::text, 'n/a') ||
         ' | ' || CASE
           WHEN latest IS NULL THEN 'never'
           WHEN EXTRACT(EPOCH FROM (NOW() - latest))/3600 > expected_h * 2 THEN 'stale'
           WHEN EXTRACT(EPOCH FROM (NOW() - latest))/3600 > expected_h     THEN 'warn'
           ELSE 'ok' END || ' |'
  FROM (
    SELECT 'gmail' AS source, (SELECT max(received_at) FROM emails) AS latest, 1 AS expected_h
    UNION ALL SELECT 'caterbook', (SELECT max(report_date)::timestamptz FROM caterbook_daily_snapshots), 24
    UNION ALL SELECT 'dojo', (SELECT max(transaction_date)::timestamptz FROM dojo_transactions), 24
    UNION ALL SELECT 'touchoffice_dept', (SELECT max(report_date)::timestamptz FROM touchoffice_department_sales), 24
    UNION ALL SELECT 'touchoffice_plu', (SELECT max(report_date)::timestamptz FROM touchoffice_plu_sales), 24
    UNION ALL SELECT 'xero', (SELECT max(ingested_at) FROM xero_bills), 168
    UNION ALL SELECT 'accommodation_bookings', (SELECT max(updated_at) FROM accommodation_bookings), 6
    UNION ALL SELECT 'restaurant_reservations', (SELECT max(reservation_at) FROM restaurant_reservations), 6
    UNION ALL SELECT 'tide_times', (SELECT max(scraped_at) FROM tide_times), 24
    UNION ALL SELECT 'guest_reviews', (SELECT max(scraped_at) FROM guest_reviews), 24
    UNION ALL SELECT 'trail_reports', (SELECT max(report_date)::timestamptz FROM trail_reports), 24
    UNION ALL SELECT 'vendor_invoice_inbox', (SELECT max(received_at) FROM vendor_invoice_inbox), 6
  ) sub ORDER BY source
) TO STDOUT
" >> /home_ai/docs/data-sources.md

# ── 4. Sitemap ──
cat > /home_ai/docs/sitemap.md <<EOF
# Sitemap

_Auto-generated by u169-gen-docs.sh. Last run: $GEN_AT._

## Frontend pages (homeai-frontend, mounted at /app)

EOF
find /home_ai/services/homeai-frontend/app -name page.tsx -type f 2>/dev/null | \
  sed 's|/home_ai/services/homeai-frontend/app||;s|/page.tsx||;s|^|- /app|' | \
  sort >> /home_ai/docs/sitemap.md

cat >> /home_ai/docs/sitemap.md <<EOF

## Build-dashboard pages (legacy, on :8090)

EOF
docker exec homeai-postgres psql -U postgres -d homeai -tAc "
COPY (
  SELECT '- ' || path FROM pageview_log
  WHERE path NOT LIKE '/api/%' AND path NOT LIKE '/static/%'
  GROUP BY path ORDER BY path
) TO STDOUT
" 2>/dev/null | head -50 >> /home_ai/docs/sitemap.md 2>/dev/null

echo "✓ generated:"
ls -la /home_ai/docs/slug-catalog.md /home_ai/docs/cron-jobs.md /home_ai/docs/data-sources.md /home_ai/docs/sitemap.md
