#!/bin/bash
# u226-gpu-recover.sh — Recover GPU containers after host NVIDIA driver change.
#
# Triggered by systemd path unit `homeai-gpu-recover.path` watching
# /var/run/cdi/nvidia.yaml (auto-regenerated by nvidia-cdi-refresh.path
# whenever the host driver or nvidia-ctk changes).
#
# What it does:
#   1. Check whether the host driver matches what GPU containers see.
#   2. If mismatch (or container exited 127 with mount-fulfil error), force
#      `docker compose up -d --force-recreate` on GPU services so they pick
#      up the freshly-regenerated CDI spec.
#   3. Telegram alert (best-effort — silent if Vault sealed).
#   4. Log to /home_ai/backups/u226-gpu-recover-<date>.log.
#
# Safe to run by hand or on a timer too. Exits 0 on no-op or success;
# non-zero only if recreation itself failed.

set -uo pipefail

COMPOSE=/home_ai/docker-compose.yml
GPU_SERVICES=(ollama build-dashboard)
LOG=/home_ai/backups/u226-gpu-recover-$(date +%Y%m%d-%H%M%S).log
mkdir -p "$(dirname "$LOG")"
exec > >(tee -a "$LOG") 2>&1

ts() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
log() { echo "[$(ts)] $*"; }

log "u226-gpu-recover start"

HOST_DRV=""
if [ -r /proc/driver/nvidia/version ]; then
  HOST_DRV=$(awk '/NVRM/ {for (i=1;i<=NF;i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {print $i; exit}}' /proc/driver/nvidia/version)
fi
log "host driver: ${HOST_DRV:-unknown}"

needs_recover=0
reasons=()

for svc in "${GPU_SERVICES[@]}"; do
  name="homeai-${svc}"
  state=$(docker inspect -f '{{.State.Status}}' "$name" 2>/dev/null || echo missing)
  exit_code=$(docker inspect -f '{{.State.ExitCode}}' "$name" 2>/dev/null || echo 0)
  err=$(docker inspect -f '{{.State.Error}}' "$name" 2>/dev/null || echo "")

  case "$state" in
    running)
      ctn_drv=$(docker exec "$name" sh -c 'nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1' 2>/dev/null || echo "")
      if [ -n "$HOST_DRV" ] && [ -n "$ctn_drv" ] && [ "$ctn_drv" != "$HOST_DRV" ]; then
        needs_recover=1
        reasons+=("$svc: driver mismatch host=$HOST_DRV container=$ctn_drv")
      else
        log "$svc: running, driver $ctn_drv (matches host)"
      fi
      ;;
    exited)
      if [ "$exit_code" = "127" ] || echo "$err" | grep -qi "libEGL_nvidia\|libcuda\|fulfil mount"; then
        needs_recover=1
        reasons+=("$svc: exited $exit_code ($err)")
      else
        log "$svc: exited $exit_code — not GPU-related, skipping"
      fi
      ;;
    missing)
      log "$svc: container missing — leaving alone (compose owns lifecycle)"
      ;;
    *)
      log "$svc: state=$state — no action"
      ;;
  esac
done

if [ "$needs_recover" = "0" ]; then
  log "no recovery needed"
  exit 0
fi

log "RECOVERING: ${reasons[*]}"

# Force-recreate so containers pick up new CDI spec / new driver libs.
if docker compose -f "$COMPOSE" up -d --force-recreate "${GPU_SERVICES[@]}" 2>&1; then
  log "compose up --force-recreate OK"
else
  rc=$?
  log "compose up FAILED rc=$rc"
  exit "$rc"
fi

# Verify
sleep 5
all_ok=1
for svc in "${GPU_SERVICES[@]}"; do
  name="homeai-${svc}"
  state=$(docker inspect -f '{{.State.Status}}' "$name" 2>/dev/null || echo missing)
  log "post-recover: $svc state=$state"
  [ "$state" = "running" ] || all_ok=0
done

# Best-effort Telegram alert. Silent if Vault is sealed or unavailable.
notify() {
  local msg="$1"
  local vault_tok
  vault_tok=$(docker inspect homeai-critical-listener --format='{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null | grep '^VAULT_TOKEN=' | cut -d= -f2-)
  [ -z "$vault_tok" ] && { log "notify: no VAULT_TOKEN — skipping telegram"; return 0; }
  docker exec -e VAULT_TOKEN="$vault_tok" -e MSG="$msg" homeai-bot-responder python3 -c "
import os, json, urllib.request
try:
    tg=json.loads(urllib.request.urlopen(urllib.request.Request('http://vault:8200/v1/secret/data/telegram',headers={'X-Vault-Token':os.environ['VAULT_TOKEN']}),timeout=5).read())['data']['data']
    urllib.request.urlopen(urllib.request.Request(f'https://api.telegram.org/bot{tg[\"bot_token\"]}/sendMessage',data=json.dumps({'chat_id':tg['chat_id'],'text':os.environ['MSG']}).encode(),headers={'Content-Type':'application/json'},method='POST'),timeout=10).read()
except Exception as e:
    print(f'notify skipped: {e}')
" 2>&1 | head -3 || log "notify: docker exec failed"
}

if [ "$all_ok" = "1" ]; then
  log "recovery succeeded"
  notify "GPU recovery (U226): driver change detected; containers recreated. ${reasons[*]}"
  exit 0
else
  log "recovery PARTIAL — some containers not running"
  notify "GPU recovery (U226) PARTIAL: ${reasons[*]} — check $LOG"
  exit 2
fi
