#!/usr/bin/env bash
# u89-gen-view-deps.sh — generate docs/views.md with dependency tree per view.
# Includes a top-30 mermaid graph of the most-referenced views.
# Read-only. Output: docs/views.md

set -euo pipefail
mkdir -p /home_ai/docs
OUT=/home_ai/docs/views.md

# Dependencies: for each view, find the relations (tables/views) it reads.
docker exec -i homeai-postgres psql -U postgres -d homeai -At -F'|' -v ON_ERROR_STOP=1 -q \
  <<'SQL' | grep -v '^$\|^SET$' > /tmp/view-deps.tsv
SET app.current_entity='all';
SELECT
    n.nspname || '.' || c.relname AS view_,
    nd.nspname || '.' || cd.relname AS dep
  FROM pg_depend d
  JOIN pg_rewrite r ON r.oid = d.objid
  JOIN pg_class c ON c.oid = r.ev_class
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_class cd ON cd.oid = d.refobjid
  JOIN pg_namespace nd ON nd.oid = cd.relnamespace
 WHERE c.relkind = 'v'
   AND cd.relkind IN ('r','v')
   AND c.oid <> cd.oid
   AND n.nspname IN ('public','mart','staging','raw')
   AND nd.nspname IN ('public','mart','staging','raw')
 ORDER BY view_, dep;
SQL

{
echo "# View dependency map"
echo ""
echo "Generated $(date -Iseconds). Auto-regenerated by \`scripts/u89-gen-view-deps.sh\`."
echo ""
nview=$(cut -d'|' -f1 /tmp/view-deps.tsv | sort -u | wc -l)
ndep=$(wc -l < /tmp/view-deps.tsv)
echo "Total views with traceable deps: $nview. Total dependency edges: $ndep."
echo ""
echo "## Most-referenced relations (top 30)"
echo ""
echo '```mermaid'
echo 'graph LR'
# Top 30 source relations by dep count, then show their views
cut -d'|' -f2 /tmp/view-deps.tsv | sort | uniq -c | sort -rn | head -30 | \
while read -r n dep; do
    # Get views depending on this source
    grep "|$dep$" /tmp/view-deps.tsv | head -3 | cut -d'|' -f1 | while read -r view; do
        # Strip schema prefix for readability; emit dep → view
        d_short=$(echo "$dep" | sed 's/^public\.//' | tr '.' '_')
        v_short=$(echo "$view" | sed 's/^public\.//' | tr '.' '_')
        echo "  $d_short --> $v_short"
    done
done | sort -u | head -60 || true
echo '```'
echo ""
echo "## Full per-view dependency list"
echo ""
prev=""
while IFS='|' read -r view dep; do
    [[ -z "$view" ]] && continue
    if [[ "$view" != "$prev" ]]; then
        echo ""
        echo "### \`$view\`"
        echo ""
        echo "Reads from:"
        prev="$view"
    fi
    echo "- \`$dep\`"
done < /tmp/view-deps.tsv
} > "$OUT"
echo "✓ wrote $OUT ($(wc -l < $OUT) lines)"
