#!/usr/bin/env bash
# u89-gen-schema-doc.sh — generate docs/schema.md from pg_catalog.
# Read-only. Idempotent. Output: docs/schema.md

set -euo pipefail
mkdir -p /home_ai/docs
OUT=/home_ai/docs/schema.md

# Pull table list
docker exec -i homeai-postgres psql -U postgres -d homeai -At -F'|' -v ON_ERROR_STOP=1 -q \
  <<'SQL' | grep -v '^$\|^SET$' > /tmp/tables.tsv
SET app.current_entity='all';
SELECT n.nspname || '.' || c.relname,
       c.relrowsecurity,
       c.reltuples::bigint
  FROM pg_class c JOIN pg_namespace n ON c.relnamespace=n.oid
 WHERE c.relkind='r' AND n.nspname IN ('public','mart','staging','raw')
   AND c.relname NOT LIKE '%_2024_%'  -- skip partition children
   AND c.relname NOT LIKE '%_2025_%'
   AND c.relname NOT LIKE '%_2026_%'
 ORDER BY 1;
SQL

{
echo "# Database schema"
echo ""
echo "Generated $(date -Iseconds). Auto-regenerated by \`scripts/u89-gen-schema-doc.sh\`."
echo ""
total=$(wc -l < /tmp/tables.tsv)
echo "Total non-partition tables: $total. Partition children (\`*_YYYY_MM\`) omitted for readability."
echo ""
echo "## Tables (alphabetical)"
echo ""

while IFS='|' read -r tbl rls reltuples; do
    [[ -z "$tbl" ]] && continue
    schema=$(echo "$tbl" | cut -d. -f1)
    name=$(echo "$tbl" | cut -d. -f2)
    rls_flag=""
    [[ "$rls" == "t" ]] && rls_flag=" 🔒 RLS"
    echo "### \`$tbl\`$rls_flag"
    echo ""
    echo "Approx rows: $reltuples"
    echo ""
    # Columns
    echo "**Columns:**"
    echo ""
    echo '| name | type | nullable | default |'
    echo '|---|---|---|---|'
    docker exec homeai-postgres psql -U postgres -d homeai -At -F'|' </dev/null -c \
        "SELECT column_name, data_type, is_nullable, coalesce(column_default,'') FROM information_schema.columns WHERE table_schema='$schema' AND table_name='$name' ORDER BY ordinal_position;" 2>/dev/null \
        | grep -v '^$\|^SET$' | head -50 | awk -F'|' '{printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4}' || true
    echo ""
    # Policies
    if [[ "$rls" == "t" ]]; then
        echo "**RLS policies:**"
        echo ""
        echo '```sql'
        docker exec homeai-postgres psql -U postgres -d homeai -At -F'|' </dev/null -c \
            "SELECT polname, CASE polpermissive WHEN true THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END FROM pg_policy WHERE polrelid = '$tbl'::regclass;" 2>/dev/null | grep -v '^$\|^SET$' || true
        echo '```'
        echo ""
    fi
done < /tmp/tables.tsv
} > "$OUT"
echo "✓ wrote $OUT ($(wc -l < $OUT) lines)"
