#!/usr/bin/env bash
# u89-gen-migration-index.sh — generate docs/migrations.md from migrations/V*.sql.
# Read-only. Output: docs/migrations.md

set -euo pipefail
mkdir -p /home_ai/docs
OUT=/home_ai/docs/migrations.md

{
echo "# Migrations index"
echo ""
echo "Generated $(date -Iseconds). Auto-regenerated by \`scripts/u89-gen-migration-index.sh\`."
echo ""
echo "| version | file | summary |"
echo "|---|---|---|"

cd /home_ai
for f in postgres/migrations/V*.sql; do
    [[ -f "$f" ]] || continue
    base=$(basename "$f")
    # Version number
    ver=$(echo "$base" | grep -oE '^V[0-9]+[a-z]?' || true)
    # Try to extract a one-line summary from the leading comment.
    # Migrations typically start with -- ====...= and then -- V## — <title>
    summary=$(awk '/^-- V[0-9]/ {sub(/^-- /, ""); print; exit}' "$f")
    if [[ -z "$summary" ]]; then
        # Fall back: first non-divider comment
        summary=$(awk 'NR>1 && /^-- [A-Z]/ && !/^-- =/ {sub(/^-- /, ""); print; exit}' "$f")
    fi
    printf "| %s | %s | %s |\n" "$ver" "$base" "${summary:-(no summary)}"
done

count=$(ls postgres/migrations/V*.sql 2>/dev/null | wc -l || true)
echo ""
echo "Total migrations: $count"
} > "$OUT"
echo "✓ wrote $OUT"
